//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 10:40:23 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://data.ws.akash.com/employee", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.akash.ws.data.employee;
